### ISSUE TITLE
add hyphenated names test

### ISSUE THREAD

**Issue by missinglink** [pelias/acceptance-tests#112]
as per https://github.com/pelias/api/issues/82

**Comment by missinglink** [comment]
`10 Max-Beer-Straße, Berlin`

**Comment by orangejulius** [comment]
We have a good selection of such tests now, including

* Arzacq-Arraziguet
* Carmel-by-the-Sea
* Saint-Die-Des-Vosges
* Les Sables-d'Olonne
* Észak-Alföld
* Île-De-France
* Dél-Dunántúl
* Közép-Magyarország
* Kasaï-Oriental

:tada:
