### ISSUE TITLE
Diversify geography & language of acceptance tests

### ISSUE THREAD

**Issue by riordan** [pelias/acceptance-tests#129]
Tests are very New-Yorky. Not that it's a bad thing to have adequate coverage of *the greatest city in the world*, but we should expand the test set to be more broadly representative and globally inclusive.

**Comment by orangejulius** [comment]
:+1:

**Comment by missinglink** [comment]
see: https://github.com/pelias/api/blob/master/test/unit/helper/labelGenerator.js for some international places

**Comment by orangejulius** [comment]
Let's call this a dupe of pelias/pelias#196
