### ISSUE TITLE
Track test results between runs (builds) and alert on failures

### ISSUE THREAD

**Issue by dianashk** [pelias/acceptance-tests#20]
Each execution of the test suite must store results along with API build id.
We then need a tool for keeping track of what has changed from one build to the next in each environment (`dev`/`stage`/`prod`). We need a clear indication of progress (`working` tests are incrementing) and possible regression (things that used to work now don't).

Each test case should be flagged with one of the following types:
 - `working` : actual == expected
 - `pending` : actual != expected, pending investigation / fix
 - `placeholder` : data is not in our data sources, or unclear if it should actually work (keep around for documentation purposes)

And here's what we need to know:
 - [ ] which tests have been added to the suite since previous execution
 - [ ] which tests used to fail and are now passing --- `YAY`
 - [ ] which tests used to pass and are now failing --- `ALERT` about this
 - [ ] which tests were changed from `pending` to `working`

Typical work flow:
 1. Begin working on an issue by selecting existing `pending` test cases and making them as `working`
 1. Write code until all `working` tests are passing in your local environment
   - run tests on `dev` and validate all `working` tests are passing
   - if any `pending` tests show up as passing mark them as `working`
 1. Promote code to `staging`
   -run tests and validate all `working` tests are passing
   - if any `pending` tests show up as passing mark them as `working`
   - do NOT merge to prod until all `working` tests are passing
 1. Promote code to `prod`
  - run tests and validate all `working` tests are passing
  - if any `pending` tests show up as passing, investigate and verify again on `staging`, this shouldn't ever happen (`staging`==`prod`)
  - do NOT merge to `prod` until all `working` tests are passing

**Comment by sevko** [comment]
Adding the expected status to each test-case (`pass`/`fail`) has the nice side-effect of relieving us from the messy problem of storing test-run histories to identify regressions. Currently have something like:
![tests](https://cloud.githubusercontent.com/assets/4467604/6641843/c7e7ce42-c976-11e4-9025-668e45158245.png)

**Comment by dianashk** [comment]
Looks good. Can we make placeholders cyan, expected failures yellow. That way red is always indicative of failure. Don't want to be desensitized to red.

**Comment by sevko** [comment]
Done in 1938555.
