### ISSUE TITLE
testing nonexistence

### ISSUE THREAD

**Issue by missinglink** [pelias/acceptance-tests#21]
would it be possible to test for the nonexistence of a document for a specific query?

in some cases it is handy to ensure that a record which was erroneously returned in the past is not returned again in the future.

some examples:

- imagine the case where a specific record is removed due to profanity, could we hit the `/doc` endpoint to ensure that it is not found?

- if a record was added to the wrong layer, could we test that it is now indexed on the correct layer & also that it no longer appears in the incorrect layer?

- if a record keeps appearing in results when it shouldn't, can we ensure that after the dev work is complete that this issue will not regress?

we'll clearly never be able to source a list of all the things that shouldn't be returned for each query but in some cases copying the 1-2 test cases from the bug reports to the regression tests will ensure that the reported error doesn't come back.

**Comment by hkrishna** [comment]
Interesting use case. +1
