### ISSUE TITLE
San Juan, Puerto Rico

### ISSUE THREAD

**Issue by trescube** [pelias/acceptance-tests#213]
First result is in Brazil, but it should be 1. instead of 2.

**Comment by orangejulius** [comment]
Looks like we've gotten even worse at [this query](http://pelias.github.io/compare/#/v1/search%3Fsources=wof&text=San%20Juan,%20Puerto%20Rico)
![screenshot_2016-07-01_16-13-27](https://cloud.githubusercontent.com/assets/111716/16533460/d6a9f750-3fa6-11e6-821a-a91233f18f4e.png)
 now:

**Comment by dianashk** [comment]
Might be resolved during the libpostal integration work.

**Comment by trescube** [comment]
We probably won't get this on initial libpostal release.  libpostal id's Puerto Rico as a country:

```
> pr

Result:

{
  "country": "pr"
}

> puerto rico

Result:

{
  "country": "puerto rico"
}
```

whereas WOF treats it as a dependency.  We'll have to do a translation between the two.

**Comment by missinglink** [comment]
@trescube says this WILL make it the libpostal release

**Comment by trescube** [comment]
The current reason this doesn't work is because, while libpostal analyzes as a city/country and that's supported by the API as a fallback query, the iso2->iso3 translation from PR->PRI doesn't match anything because the dependency_a value for Puerto Rico is PR.
