### ISSUE TITLE
Untracked file: .validate.json

### ISSUE THREAD

**Issue by missinglink** [pelias/acceptance-tests#34]
After a fresh clone and an `npm install` a file called `.validate.json` appears in my working directory.

```bash
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	.validate.json
```

**Comment by sevko** [comment]
This was apparently introduced in version 2.0.0+ of [precommit-hook](https://www.npmjs.com/package/precommit-hook). I'll revert to 1.0.7, which we use elsewhere.
