### ISSUE TITLE
Test against large external data sets

### ISSUE THREAD

**Issue by missinglink** [pelias/acceptance-tests#39]
There are some dataset available via creative commons such as http://dev.maxmind.com/geoip/geoip2/geolite2/ which can be used to generate testcases which cover every city in the world.

**Comment by missinglink** [comment]
http://wiki.openstreetmap.org/wiki/Nominatim/TestCases

**Comment by orangejulius** [comment]
I do believe we have this one covered with pelias/fuzzy-tests now :)
