### ISSUE TITLE
Change index name

### ISSUE THREAD

**Issue by Binternet** [pelias/acceptance-tests#464]
The tests are hitting
`curl http://192.168.29.76:9200//search?text=Tajura%27%20wa%20an%20Nawahi%20al%20Arba%2C%20LY&sources=wof`

when my index name is `pelias`, how can I change that?

**Comment by orangejulius** [comment]
Hey @Binternet,
The acceptance tests are meant to run against the [api service](https://github.com/pelias/api), not Elasticsearch directly.

**Comment by missinglink** [comment]
related: https://github.com/pelias/api/issues/1103
