### ISSUE TITLE
Come up with a new name for the api_key config section

### ISSUE THREAD

**Issue by orangejulius** [pelias/acceptance-tests#465]
As specified in the README, the way to configure API keys for servers to run acceptance tests is to put them in a `mapzen` section of `pelias.json`. Obviously, this is no longer the most relevant name.

```
{
  "mapzen": {
    "api_key": {
      "search.mapzen.com": "search-XXXXXX"
    }
  },
  "acceptance-tests": {
    "endpoints": {
      "prod": "http://search.mapzen.com/v1/"
    }
  }
}
```

We should add an alternate key name (supporting the old key for backwards compatibility), that is more relevant going forward.

Connects https://github.com/pelias/pelias/issues/703

**Comment by otbutz** [comment]
`credentials`?

**Comment by orangejulius** [comment]
`credentials` is perfect.

If anyone's looking for a good starter PR, allowing the [fuzzy-tester](https://github.com/pelias/fuzzy-tester) to look for `credentials` in the old location (`mapzen.api_key`) and new location `credentials.api_key`) would be a good one.
