### ISSUE TITLE
exclude 'feedback' test cases

### ISSUE THREAD

**Issue by missinglink** [pelias/acceptance-tests#93]
it would be handy if I could run the tests *without* also running all the 'feedback' cases, my current hacky solution is:

```bash
> rm test_cases/feedback*
> node test -e stage
> git checkout test_cases/feedback*
```

maybe we could add an 'exclude' flag to the cli?

**Comment by orangejulius** [comment]
I was thinking earlier today while reviewing test PRs. A super simple initial way to improve our testing might just be to move the feedback tests to their own repo. Any tests that aren't clear cut enough to get our blessing move from acceptance-tests to feedback-tests. Then we just track the percentage passing in feedback-tests as a rough indicator of quality.

**Comment by orangejulius** [comment]
Also #111 could address this nicely.

**Comment by orangejulius** [comment]
This is done now because we've moved them all to the fuzzy-tests repo
