### ISSUE TITLE
[reporter] expected failed tests marked as improvement

### ISSUE THREAD

**Issue by missinglink** [pelias/acceptance-tests#95]
I marked a test as 'status:fail' and now it's showing as an 'improvement'?

```bash
  ✔ improvement [2] "{"input":"bronx","layers":"admin2"}"
```

**Comment by orangejulius** [comment]
That means its passing, but we expect it to fail, which the tests count as a good thing. I think we should get rid of the status tag all together, all tests should be expected to pass, even if how we handle the failure is different for different tests.
